- name: creating the simple condition
  hosts: web1
  tasks:
  - name: checking the length of the string and printing the values
    ansible.builtin.debug:
      msg: "the name you entered is {{user_name}} and the password is {{password}}"
 