- name: for the lists
  hosts: localhost
  vars:
    friend_names:
      - mohan
      - chiru
      - vijay
  tasks:
  - name: performing the operations on lists
    ansible.builtin.debug:
      msg: " you have total {{(friend_names |length)+1}}"