- name: primtpign  the variables
  hosts: web1
  tasks:
  - name: gettring and display the username 
    ansible.builtin.debug:
      msg: "the username is {{user_name}} and the passwrod is {{passwrod}}"