- name: for the lists
  hosts: localhost
  vars:
    friend_names: [1.2,3.4,5.6]
  tasks:
  - name: performing the operations on lists
    ansible.builtin.debug:
      msg: " you have total {{friend_names | map('abs')}}"