- name: for the lists
  hosts: localhost
  vars:
    friend_names: ["mohan","vijay","chiru"]
  tasks:
  - name: performing the operations on lists
    ansible.builtin.debug:
      msg: " you have total {{friend_names | join(',')}}"