- name: for the lists
  hosts: localhost
  vars:
    list1:
      - 1
      - 2
      - 3
    list2:
      - 4
      - 5
      - 6
  tasks:
  - name: performing the operations on lists
    ansible.builtin.debug:
      msg: " you have total {{list1 |product(list2)}}"