- name: checking the variables
  hosts: localhost
  vars:
    name: "mohan"
    age: [1,2,3,4,5,6,7,8]
  tasks:
  - name: pringitn the variables
    ansible.builtin.debug:
      msg: "my name is {{name}} and my age is {{age}}"