- name: primtpign  the variables
  hosts: localhost
  vars_prompt:
  - name: username
    prompt: enter the username
    private: false
  - name: passwrod
    prompt: please enteer the passwrod
    private: true
  tasks:
  - name: gettring and display the username 
    ansible.builtin.debug:
      msg: "the username is {{username}} and the passwrod is {{passwrod}}"