- name: using the register to get the value of the previuos command
  hosts: localhost
  tasks:
  - name: creating the user
    ansible.builtin.command: id mohan
    register: username
    ignore_errors: true
  - name: printitng the variables
    ansible.builtin.debug:
      msg: 'the message is {{username}}'