- name: my name is mohan
  hosts: localhost
  tasks:
  - name: printing the variable
    become: yes
    ansible.builtin.yum:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: nginx ,state: installed}
    - {name: postman, state: installed}
