- name: setting up the catalogue service
  hosts: catalogue
  become: yes
  tasks: 
  - name: installing the code from the aws s3
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"
  - name: installing the nodejs 
    ansible.builtin.yum:
      name: nodejs
      state: installed
  - name: check the robosop user exist or not 
    ansible.builtin.command: id robosop
    register: out
    ignore_errors: true

  - name: printing theoutput
    ansible.builtin.debug:
      msg: "output is {{out}}"

  - when: out.rc !=0
    name: creating the robohopo user
    become: yes
    ansible.builtin.user:
      name: robohopo
  - name: check the app directory
    ansible.builtin.stat:
      path: /app
    register: directory

  - name: priting the directory stats
    ansible.builtin.debug:
      msg: "output{{directory}}"
  - when: directory.stat.exists == false
    name: creating the directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: download the catalogue artifact
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp
  - name: extract the catalogue component
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
  

  
