- name: setting up the webserver for the our website
  hosts: web
  tasks:
  - name: installing the nginx
    become: yes
    ansible.builtin.yum:
      name: nginx
      state: installed
  - name: strting the server
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: true